version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 875525659788.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - cd ia
      - docker build -t service20:latest .
      - cd ../iaf
      - docker build -t service21:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker tag service20:latest 875525659788.dkr.ecr.us-east-1.amazonaws.com/service20:latest
      - docker tag service21:latest 875525659788.dkr.ecr.us-east-1.amazonaws.com/service21:latest
      - docker push 875525659788.dkr.ecr.us-east-1.amazonaws.com/service20:latest
      - docker push 875525659788.dkr.ecr.us-east-1.amazonaws.com/service21:latest
      - echo Writing image definitions file...
      - echo "875525659788.dkr.ecr.us-east-1.amazonaws.com/service20:latest" > service-1.json 
      - echo "875525659788.dkr.ecr.us-east-1.amazonaws.com/service21:latest" > service-2.json 
      - ls -la

artifacts:
  files:
    - "**/*"
